app:
    mode: dev
    port: 8080
    domain: example.com
    tls:
        status: off
        pemPath: cert/server.pem
        keyPath: cert/server.key

log:
    level: info
    path: var/logs

redis:
    addr: localhost:6379
    password:
    db: 0

github:
    webhook_secret: value
    client_id: value
    client_secret: value
    redirect_uri: http://app_url/auth
    allow_signup: false
    scopes:
        - repo